version: "3"

services:
  app-pg:
    image: postgres:12-alpine
    container_name: feature-flagger-db
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    ports:
      - "5432:5432"
  app-redis:
    image: redis:latest
    container_name: feature-flagger-redis
  app:
    build: .
    container_name: feature-flagger
    command: "rails s -b 0.0.0.0"
    ports:
      - "3000:3000"
    volumes:
      - .:/ruby/src
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_HOST: feature-flagger-db
      POSTGRES_DB: docker
      REDIS_HOST: feature-flagger-redis
    links:
      - app-pg
      - app-redis

